fix: modify source pr for main to only allow pr's from develop.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,8 +4,19 @@ on:
         branches:
             - main  
 jobs:
+
+    validate_branch:
+        runs-on: ubuntu-latest
+        steps:
+            - name: Check PR source branch
+              run: |
+                if [[ "${{ github.head_ref }}" != "develop" ]]; then
+                  echo "❌ ERROR: Pull requests to main must come from develop!"
+                  exit 1
+                fi
+
     build_ipa:
-        if: github.head_ref == 'develop'  
+        needs: validate_branch
         runs-on: macos-latest
         steps:
             - name: Checkout repository
@@ -31,7 +42,7 @@ jobs:
                 path: |
                   build/ios_build.tar.gz
     build_apk:
-        if: github.head_ref == 'develop'  
+        needs: validate_branch
         runs-on: ubuntu-latest
         steps:
             - name: Checkout repository
